//! Never-panic suite for the whole pid-parse chain on mutated drawings.
//!
//! Feature: pid-import-next-round, Property 1: pid-parse 解析链对任意变异输入不 panic、不挂起、不超额分配
//!
//! **Validates: Requirements 4.1, 4.3, 4.4, 4.5, 4.6, 4.7**
//!
//! `tests/parser_panic_safety.rs` feeds a small adversarial corpus to each
//! byte-level parser on its own. This suite drives the chain
//! OpenCADStudio's `.pid` importer runs on a buffer —
//! `PidParser::with_options(ParseOptions::geometry()).parse_reader`, then on
//! `Ok` `build_normalized_geometry` and the `style_link` entry points — over
//! generated bytes and the six corpus drawings under `test-file/`, each put
//! through one of six mutations (design D2):
//!
//! | class | parameters |
//! |---|---|
//! | empty | `[]` |
//! | random bytes | `len` = 1, 7, 8, 511, 512, 513, 4096, 65 536, random ≤ 1 MiB |
//! | truncate | `at` = 0, 8, 76, 511, 512, 513, 4096, `len / 2`, `len - 1`, random |
//! | flip bytes | 1, 4 or 32 seeded offsets, each XORed with a non-zero byte |
//! | zero a sector | 512-byte sector 0 (the CFB header), 1, random |
//! | huge length | 1–8 seeded 4-byte-aligned offsets, or one CFB header count field (`0x2C` `0x30` `0x3C` `0x40` `0x44` `0x48`), set to `0xFFFF_FFFF` / `0xFFFF_FFFE` / `0x8000_0000` / `0x7FFF_FFFF` / `0x0100_0000` |
//!
//! Every case runs on its own thread and must come back `Ok` or `Err` within
//! 10 s, without panicking, and without any single allocation above the cap:
//! `max(64 MiB, 8 × the largest allocation the six unmutated drawings make)`.
//! The cap is measured, not picked — `the_six_originals_set_the_allocation_cap`
//! prints the per-drawing peaks it comes from.
//!
//! Batches:
//!
//! - default, about 100 cases (empty 1 + random 9 + 15 per drawing):
//!   `cargo test --test arbitrary_bytes_never_panic`;
//! - extended, `#[ignore]`d, 100 generated + 500 per drawing:
//!   `cargo test --release --test arbitrary_bytes_never_panic -- --ignored`.
//!   Debug catches integer-overflow panics a release build wraps past;
//!   release reaches the huge allocations and hangs that wrapping leads to.
//!
//! A case is `(source, mutation, seed)`; its seed is
//! `splitmix64(base seed ^ case index)`, and the same triple always builds
//! the same bytes (each case is built twice and compared). Knobs:
//!
//! - `PID_NEVER_PANIC_SEED` replaces the base seed (decimal or `0x` hex) to
//!   explore; failures still print their seed.
//! - `PID_NEVER_PANIC_SKIP` lists case indices to leave out
//!   (comma-separated), for walking past a case that aborts the process.
//!
//! Reading a failure: one line per case,
//! `<file> <mutation> <params> seed=0x…: <reason>`, all reported at once. A
//! batch stops after 3 hangs, because each hung case leaks its thread. A case
//! that aborts the whole process (an allocation even the OS refuses, a stack
//! overflow) takes the report with it: rerun with
//! `-- --nocapture --test-threads=1`, and the last `case i:` line names it.
//!
//! The allocation counter is process-wide, so every test here holds
//! [`SERIAL`]; the default and extended batches never share a process
//! (`--ignored` runs the extended batch alone).

use std::alloc::{GlobalAlloc, Layout, System};
use std::fmt;
use std::hint::black_box;
use std::io::Cursor;
use std::path::Path;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::mpsc::{self, RecvTimeoutError};
use std::sync::{Mutex, MutexGuard, Once, OnceLock, PoisonError};
use std::thread;
use std::time::{Duration, Instant};

use pid_parse::style_link::{self, TextRunStatus};
use pid_parse::{build_normalized_geometry, ParseOptions, PidParser};

/// Base seed of both batches; [`SEED_VAR`] replaces it.
const BASE_SEED: u64 = 0x5EED_0929;
const SEED_VAR: &str = "PID_NEVER_PANIC_SEED";
const SKIP_VAR: &str = "PID_NEVER_PANIC_SKIP";

/// How long one case may take before it counts as hung.
const CASE_TIMEOUT: Duration = Duration::from_secs(10);
/// Hung cases after which a batch stops: every one leaks a busy thread.
const MAX_HANGS: usize = 3;
/// The allocation cap is `max(CAP_FLOOR, CAP_FACTOR × the originals' peak)`.
const CAP_FLOOR: usize = 64 << 20;
const CAP_FACTOR: usize = 8;

const SECTOR: usize = 512;
const PAGE: usize = 4096;
const MAX_RANDOM_LEN: usize = 1 << 20;
const RANDOM_LENGTHS: [usize; 8] = [1, 7, 8, 511, 512, 513, 4096, 65_536];
const HUGE_VALUES: [u32; 5] = [
    0xFFFF_FFFF,
    0xFFFF_FFFE,
    0x8000_0000,
    0x7FFF_FFFF,
    0x0100_0000,
];
/// CFB header count fields: FAT sectors, first directory sector, first
/// mini-FAT sector, mini-FAT sectors, first DIFAT sector, DIFAT sectors.
const HEADER_FIELDS: [usize; 6] = [0x2C, 0x30, 0x3C, 0x40, 0x44, 0x48];

/// Random-length byte strings in the extended batch beyond the fixed nine
/// generated cases, making 100 generated cases.
const EXTENDED_RANDOM_DRAWS: usize = 91;
/// Cases per drawing in the extended batch.
const EXTENDED_PER_FILE: usize = 500;

/// The corpus, relative to `test-file/` (git-ignored; missing drawings are
/// skipped with a note).
const ORIGINALS: [&str; 6] = [
    "D06.pid",
    "DWG-0201GP06-01.pid",
    "DWG-0202GP06-01.pid",
    "工艺管道及仪表流程-1.pid",
    "export-test/publish-data/A01/A01.pid",
    "export-test/publish-data/DWG-0202GP06-01/DWG-0202GP06-01.pid",
];

/// The default batch's fifteen per drawing: these fourteen, plus one header
/// count field taken in turn so the six drawings cover all six fields.
const DEFAULT_PICKS: [Pick; 14] = [
    Pick::TruncateAt(76),
    Pick::TruncateAt(511),
    Pick::TruncateAt(512),
    Pick::TruncateAt(PAGE),
    Pick::TruncateHalf,
    Pick::TruncateLast,
    Pick::TruncateAnywhere,
    Pick::Flip(1),
    Pick::Flip(4),
    Pick::Flip(32),
    Pick::ZeroSector(0),
    Pick::ZeroSector(1),
    Pick::ZeroAnySector,
    Pick::HugeAnywhere,
];

/// The extended batch runs every parameter the seed does not change once per
/// drawing (these, then each header field)...
const FIXED_PICKS: [Pick; 11] = [
    Pick::TruncateAt(0),
    Pick::TruncateAt(8),
    Pick::TruncateAt(76),
    Pick::TruncateAt(511),
    Pick::TruncateAt(512),
    Pick::TruncateAt(513),
    Pick::TruncateAt(PAGE),
    Pick::TruncateHalf,
    Pick::TruncateLast,
    Pick::ZeroSector(0),
    Pick::ZeroSector(1),
];

/// ...then these in turn until the drawing has [`EXTENDED_PER_FILE`] cases.
const SEEDED_PICKS: [Pick; 6] = [
    Pick::TruncateAnywhere,
    Pick::Flip(1),
    Pick::Flip(4),
    Pick::Flip(32),
    Pick::ZeroAnySector,
    Pick::HugeAnywhere,
];

// ---------------------------------------------------------------------------
// Generator
// ---------------------------------------------------------------------------

fn splitmix64(seed: u64) -> u64 {
    let mut z = seed.wrapping_add(0x9E37_79B9_7F4A_7C15);
    z = (z ^ (z >> 30)).wrapping_mul(0xBF58_476D_1CE4_E5B9);
    z = (z ^ (z >> 27)).wrapping_mul(0x94D0_49BB_1331_11EB);
    z ^ (z >> 31)
}

/// Seeded xorshift64 (P-D22). The seed goes through splitmix64 first, and
/// `| 1` keeps the state non-zero.
struct XorShift64(u64);

impl XorShift64 {
    fn new(seed: u64) -> Self {
        Self(splitmix64(seed) | 1)
    }

    fn next_u64(&mut self) -> u64 {
        let mut x = self.0;
        x ^= x << 13;
        x ^= x >> 7;
        x ^= x << 17;
        self.0 = x;
        x
    }

    /// In `[0, n)`; 0 when `n` is 0. The modulo bias does not matter here.
    fn below(&mut self, n: usize) -> usize {
        if n == 0 {
            0
        } else {
            (self.next_u64() % n as u64) as usize
        }
    }
}

/// Where [`Mutation::HugeLength`] writes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Slots {
    /// `count` seeded 4-byte-aligned offsets anywhere in the file.
    Random { count: usize },
    /// One CFB header count field, by offset.
    HeaderField { offset: usize },
}

/// One of the six mutation classes, with every parameter drawn: the printed
/// form plus the seed rebuilds the case's bytes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum Mutation {
    Empty,
    Random {
        len: usize,
    },
    Truncate {
        at: usize,
    },
    FlipBytes {
        count: usize,
    },
    /// 512-byte sectors, counted from the start of the file.
    ZeroSector {
        sector: usize,
    },
    /// Writes one of [`HUGE_VALUES`], little-endian, per slot.
    HugeLength {
        at: Slots,
    },
}

impl fmt::Display for Mutation {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match *self {
            Mutation::Empty => f.write_str("empty"),
            Mutation::Random { len } => write!(f, "random len={len}"),
            Mutation::Truncate { at } => write!(f, "truncate at={at}"),
            Mutation::FlipBytes { count } => write!(f, "flip-bytes count={count}"),
            Mutation::ZeroSector { sector } => write!(f, "zero-sector sector={sector}"),
            Mutation::HugeLength {
                at: Slots::Random { count },
            } => write!(f, "huge-length count={count}"),
            Mutation::HugeLength {
                at: Slots::HeaderField { offset },
            } => write!(f, "huge-length field=0x{offset:02X}"),
        }
    }
}

/// Pure: the same `(source, mutation, seed)` always builds the same bytes
/// (requirement 4.4).
fn build(source: &[u8], mutation: &Mutation, seed: u64) -> Vec<u8> {
    let mut rng = XorShift64::new(seed);
    match *mutation {
        Mutation::Empty => Vec::new(),
        Mutation::Random { len } => {
            let mut out = Vec::with_capacity(len);
            while out.len() < len {
                let word = rng.next_u64().to_le_bytes();
                let take = (len - out.len()).min(word.len());
                out.extend_from_slice(&word[..take]);
            }
            out
        }
        Mutation::Truncate { at } => source[..at.min(source.len())].to_vec(),
        Mutation::FlipBytes { count } => {
            let mut out = source.to_vec();
            if !out.is_empty() {
                for _ in 0..count {
                    let at = rng.below(out.len());
                    // 1..=255: a flip that always changes the byte.
                    out[at] ^= (1 + rng.below(255)) as u8;
                }
            }
            out
        }
        Mutation::ZeroSector { sector } => {
            let mut out = source.to_vec();
            let start = sector.saturating_mul(SECTOR).min(out.len());
            let end = start.saturating_add(SECTOR).min(out.len());
            out[start..end].fill(0);
            out
        }
        Mutation::HugeLength { at } => {
            let mut out = source.to_vec();
            match at {
                Slots::Random { count } => {
                    for _ in 0..count {
                        let offset = rng.below(out.len() / 4) * 4;
                        write_huge(&mut out, offset, &mut rng);
                    }
                }
                Slots::HeaderField { offset } => write_huge(&mut out, offset, &mut rng),
            }
            out
        }
    }
}

/// Overwrite the `u32` at `offset` with a seeded [`HUGE_VALUES`] entry; a
/// no-op when the four bytes are not all there.
fn write_huge(bytes: &mut [u8], offset: usize, rng: &mut XorShift64) {
    let value = HUGE_VALUES[rng.below(HUGE_VALUES.len())];
    if let Some(slot) = bytes.get_mut(offset..offset.saturating_add(4)) {
        slot.copy_from_slice(&value.to_le_bytes());
    }
}

/// A drawing-level mutation before the parameters that depend on the
/// drawing's length or on the seed are drawn.
#[derive(Debug, Clone, Copy)]
enum Pick {
    TruncateAt(usize),
    TruncateHalf,
    TruncateLast,
    TruncateAnywhere,
    Flip(usize),
    ZeroSector(usize),
    ZeroAnySector,
    HugeAnywhere,
    HugeField(usize),
}

impl Pick {
    fn resolve(self, len: usize, rng: &mut XorShift64) -> Mutation {
        match self {
            Pick::TruncateAt(at) => Mutation::Truncate { at: at.min(len) },
            Pick::TruncateHalf => Mutation::Truncate { at: len / 2 },
            Pick::TruncateLast => Mutation::Truncate {
                at: len.saturating_sub(1),
            },
            Pick::TruncateAnywhere => Mutation::Truncate { at: rng.below(len) },
            Pick::Flip(count) => Mutation::FlipBytes { count },
            Pick::ZeroSector(sector) => Mutation::ZeroSector { sector },
            Pick::ZeroAnySector => Mutation::ZeroSector {
                sector: rng.below(len.div_ceil(SECTOR)),
            },
            Pick::HugeAnywhere => Mutation::HugeLength {
                at: Slots::Random {
                    count: 1 + rng.below(8),
                },
            },
            Pick::HugeField(offset) => Mutation::HugeLength {
                at: Slots::HeaderField { offset },
            },
        }
    }
}

// ---------------------------------------------------------------------------
// Cases and plans
// ---------------------------------------------------------------------------

/// A corpus drawing, read once.
struct Original {
    name: &'static str,
    bytes: Vec<u8>,
}

/// The drawings under `test-file/` that are checked out.
fn corpus() -> &'static [Original] {
    static CORPUS: OnceLock<Vec<Original>> = OnceLock::new();
    CORPUS.get_or_init(|| {
        let root = Path::new(env!("CARGO_MANIFEST_DIR")).join("test-file");
        ORIGINALS
            .iter()
            .filter_map(|&name| match std::fs::read(root.join(name)) {
                Ok(bytes) => Some(Original { name, bytes }),
                Err(err) => {
                    eprintln!("skip {name}: {err} (test-file/ is git-ignored)");
                    None
                }
            })
            .collect()
    })
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct Case {
    index: usize,
    /// Index into [`corpus`]; `None` for generated bytes.
    file: Option<usize>,
    mutation: Mutation,
    seed: u64,
}

impl Case {
    fn source<'a>(&self, corpus: &'a [Original]) -> &'a [u8] {
        match self.file {
            Some(file) => corpus[file].bytes.as_slice(),
            None => &[],
        }
    }

    /// `<file> <mutation> <params> seed=0x…`
    fn line(&self, corpus: &[Original]) -> String {
        let file = self.file.map_or("(generated)", |file| corpus[file].name);
        format!("{file} {} seed=0x{:016X}", self.mutation, self.seed)
    }
}

struct Planner {
    base: u64,
    cases: Vec<Case>,
}

impl Planner {
    fn new(base: u64) -> Self {
        Self {
            base,
            cases: Vec::new(),
        }
    }

    fn push(&mut self, file: Option<usize>, draw: impl FnOnce(&mut XorShift64) -> Mutation) {
        let index = self.cases.len();
        let seed = splitmix64(self.base ^ index as u64);
        // Parameters come from a stream apart from the one `build` draws.
        let mutation = draw(&mut XorShift64::new(!seed));
        self.cases.push(Case {
            index,
            file,
            mutation,
            seed,
        });
    }

    /// Empty, the fixed random lengths, then `draws` random lengths ≤ 1 MiB.
    fn generated(&mut self, draws: usize) {
        self.push(None, |_| Mutation::Empty);
        for len in RANDOM_LENGTHS {
            self.push(None, move |_| Mutation::Random { len });
        }
        for _ in 0..draws {
            self.push(None, |rng| Mutation::Random {
                len: 1 + rng.below(MAX_RANDOM_LEN),
            });
        }
    }

    fn drawing(&mut self, file: usize, len: usize, pick: Pick) {
        self.push(Some(file), |rng| pick.resolve(len, rng));
    }
}

/// About 100 cases: empty 1 + random 9 + 15 per drawing.
fn default_plan(base: u64, corpus: &[Original]) -> Vec<Case> {
    let mut plan = Planner::new(base);
    plan.generated(1);
    for (file, original) in corpus.iter().enumerate() {
        let len = original.bytes.len();
        for pick in DEFAULT_PICKS {
            plan.drawing(file, len, pick);
        }
        let field = HEADER_FIELDS[file % HEADER_FIELDS.len()];
        plan.drawing(file, len, Pick::HugeField(field));
    }
    plan.cases
}

/// Thousands of cases: 100 generated + [`EXTENDED_PER_FILE`] per drawing.
fn extended_plan(base: u64, corpus: &[Original]) -> Vec<Case> {
    let mut plan = Planner::new(base);
    plan.generated(EXTENDED_RANDOM_DRAWS);
    for (file, original) in corpus.iter().enumerate() {
        let len = original.bytes.len();
        let fixed: Vec<Pick> = FIXED_PICKS
            .into_iter()
            .chain(HEADER_FIELDS.into_iter().map(Pick::HugeField))
            .collect();
        let seeded = SEEDED_PICKS
            .into_iter()
            .cycle()
            .take(EXTENDED_PER_FILE.saturating_sub(fixed.len()));
        for pick in fixed.iter().copied().chain(seeded) {
            plan.drawing(file, len, pick);
        }
    }
    plan.cases
}

fn base_seed() -> u64 {
    match std::env::var(SEED_VAR) {
        Ok(text) => parse_seed(&text)
            .unwrap_or_else(|| panic!("{SEED_VAR}={text:?} is not a u64 (decimal or 0x hex)")),
        Err(_) => BASE_SEED,
    }
}

fn parse_seed(text: &str) -> Option<u64> {
    let text = text.trim().replace('_', "");
    match text.strip_prefix("0x").or_else(|| text.strip_prefix("0X")) {
        Some(hex) => u64::from_str_radix(hex, 16).ok(),
        None => text.parse().ok(),
    }
}

fn skipped_cases() -> Vec<usize> {
    let Ok(text) = std::env::var(SKIP_VAR) else {
        return Vec::new();
    };
    text.split(',')
        .map(str::trim)
        .filter(|part| !part.is_empty())
        .map(|part| {
            part.parse()
                .unwrap_or_else(|_| panic!("{SKIP_VAR}: {part:?} is not a case index"))
        })
        .collect()
}

// ---------------------------------------------------------------------------
// The chain under test
// ---------------------------------------------------------------------------

/// The chain OpenCADStudio's importer runs on a buffer (`import()` in
/// `src/io/pid/mod.rs`, and `styles.rs`), minus
/// `PidSemanticIndex::load_beside`, which the bytes route never calls.
/// `black_box` keeps a release build from dropping work nobody reads.
/// Returns whether `parse_reader` said `Ok`.
fn pid_parse_chain(bytes: &[u8]) -> bool {
    let parsed = PidParser::with_options(ParseOptions::geometry()).parse_reader(Cursor::new(bytes));
    // `Err` is an answer too: the case ends there.
    let Ok(doc) = parsed else {
        return false;
    };
    black_box(build_normalized_geometry(&doc));
    black_box(doc.style_tables.get("/").map(|table| table.is_empty()));
    black_box(style_link::line_styles_for_document(&doc));
    black_box(style_link::style_names_for_document(&doc));
    black_box(style_link::style_libraries_for_document(&doc));
    let text_styles = style_link::text_styles_for_document(&doc);
    for style in text_styles.values() {
        black_box(style.effective());
        black_box(matches!(style.runs, TextRunStatus::Flattened { .. }));
    }
    black_box(text_styles);
    black_box(style_link::fill_styles_for_document(&doc));
    true
}

// ---------------------------------------------------------------------------
// Executor and allocation watch
// ---------------------------------------------------------------------------

/// Records the largest single request since the last reset, and never
/// refuses one: a `GlobalAlloc` must not unwind, so the verdict is passed
/// after the case returns.
struct Watch;

static LARGEST: AtomicUsize = AtomicUsize::new(0);

// SAFETY: every method forwards its arguments to `System` unchanged; the
// only addition is a relaxed atomic max, which neither allocates nor unwinds.
unsafe impl GlobalAlloc for Watch {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        LARGEST.fetch_max(layout.size(), Ordering::Relaxed);
        // SAFETY: the caller upholds `GlobalAlloc::alloc`'s contract.
        unsafe { System.alloc(layout) }
    }

    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        LARGEST.fetch_max(layout.size(), Ordering::Relaxed);
        // SAFETY: the caller upholds `GlobalAlloc::alloc_zeroed`'s contract.
        unsafe { System.alloc_zeroed(layout) }
    }

    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        LARGEST.fetch_max(new_size, Ordering::Relaxed);
        // SAFETY: the caller upholds `GlobalAlloc::realloc`'s contract.
        unsafe { System.realloc(ptr, layout, new_size) }
    }

    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        // SAFETY: the caller upholds `GlobalAlloc::dealloc`'s contract.
        unsafe { System.dealloc(ptr, layout) }
    }
}

#[global_allocator]
static WATCH: Watch = Watch;

/// Held by every test: [`LARGEST`] is process-wide.
static SERIAL: Mutex<()> = Mutex::new(());

/// Where the last named thread panicked: the payload alone does not say.
static PANIC_AT: Mutex<Option<(String, String)>> = Mutex::new(None);

/// A poisoned lock only means an earlier test failed while holding it.
fn lock<T>(mutex: &Mutex<T>) -> MutexGuard<'_, T> {
    mutex.lock().unwrap_or_else(PoisonError::into_inner)
}

/// Chain a hook in front of the default one that notes the panic location.
fn install_panic_hook() {
    static ONCE: Once = Once::new();
    ONCE.call_once(|| {
        let default_hook = std::panic::take_hook();
        std::panic::set_hook(Box::new(move |info| {
            let current = thread::current();
            if let (Some(name), Some(at)) = (current.name(), info.location()) {
                *lock(&PANIC_AT) = Some((name.to_owned(), at.to_string()));
            }
            default_hook(info);
        }));
    });
}

#[derive(Debug)]
enum Failure {
    Panicked(String),
    Hung,
    OverAllocated { largest: usize, cap: usize },
}

impl fmt::Display for Failure {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Failure::Panicked(text) => f.write_str(text),
            Failure::Hung => write!(f, "hung > {} s", CASE_TIMEOUT.as_secs()),
            Failure::OverAllocated { largest, cap } => {
                write!(f, "largest allocation {largest} B > cap {cap} B")
            }
        }
    }
}

/// What a case that passed did.
#[derive(Debug, Clone, Copy)]
struct Passed {
    /// `parse_reader` said `Ok`, so the rest of the chain ran.
    parsed: bool,
    /// Largest single allocation while the case ran.
    largest: usize,
}

/// Run `pipeline` over `bytes` on a thread named `label`: a panic surfaces
/// as a closed channel, a hang as a timeout (the thread is leaked).
fn run_case(
    label: &str,
    bytes: Vec<u8>,
    cap: usize,
    pipeline: fn(&[u8]) -> bool,
) -> Result<Passed, Failure> {
    install_panic_hook();
    *lock(&PANIC_AT) = None;
    LARGEST.store(0, Ordering::Relaxed);
    let (tx, rx) = mpsc::channel();
    let handle = thread::Builder::new()
        .name(label.to_owned())
        .spawn(move || {
            let parsed = pipeline(&bytes);
            let _ = tx.send(parsed);
        })
        .expect("spawn a case thread");
    match rx.recv_timeout(CASE_TIMEOUT) {
        Ok(parsed) => {
            let _ = handle.join();
            let largest = LARGEST.load(Ordering::Relaxed);
            if largest > cap {
                Err(Failure::OverAllocated { largest, cap })
            } else {
                Ok(Passed { parsed, largest })
            }
        }
        Err(RecvTimeoutError::Disconnected) => {
            Err(Failure::Panicked(panic_text(handle.join(), label)))
        }
        Err(RecvTimeoutError::Timeout) => Err(Failure::Hung),
    }
}

/// `panicked at <file:line:col>: <message>`, on one line.
fn panic_text(joined: thread::Result<()>, label: &str) -> String {
    let message = match joined {
        Ok(()) => return "the case thread ended without reporting back".to_owned(),
        Err(payload) => payload
            .downcast_ref::<&str>()
            .map(|text| (*text).to_owned())
            .or_else(|| payload.downcast_ref::<String>().cloned())
            .unwrap_or_else(|| "(a panic payload that is not a string)".to_owned()),
    };
    let message = message.lines().collect::<Vec<_>>().join(" / ");
    let at = lock(&PANIC_AT)
        .take()
        .filter(|(thread, _)| thread == label)
        .map(|(_, at)| at);
    match at {
        Some(at) => format!("panicked at {at}: {message}"),
        None => format!("panicked: {message}"),
    }
}

// ---------------------------------------------------------------------------
// Baseline and batches
// ---------------------------------------------------------------------------

struct Measured {
    name: &'static str,
    outcome: Result<Passed, Failure>,
    elapsed: Duration,
}

struct Baseline {
    originals: Vec<Measured>,
    /// The largest allocation any unmutated drawing made.
    peak: usize,
    cap: usize,
}

impl Baseline {
    fn cap_text(&self) -> String {
        format!(
            "max({} MiB, {} B × {CAP_FACTOR}) = {} B",
            CAP_FLOOR >> 20,
            self.peak,
            self.cap
        )
    }
}

/// The six unmutated drawings, measured once per process. Callers hold
/// [`SERIAL`].
fn baseline() -> &'static Baseline {
    static BASELINE: OnceLock<Baseline> = OnceLock::new();
    BASELINE.get_or_init(|| {
        let originals: Vec<Measured> = corpus()
            .iter()
            .enumerate()
            .map(|(file, original)| {
                let started = Instant::now();
                let outcome = run_case(
                    &format!("original {file}"),
                    original.bytes.clone(),
                    usize::MAX,
                    pid_parse_chain,
                );
                Measured {
                    name: original.name,
                    outcome,
                    elapsed: started.elapsed(),
                }
            })
            .collect();
        let peak = originals
            .iter()
            .filter_map(|measured| measured.outcome.as_ref().ok())
            .map(|passed| passed.largest)
            .max()
            .unwrap_or(0);
        Baseline {
            originals,
            peak,
            cap: CAP_FLOOR.max(peak.saturating_mul(CAP_FACTOR)),
        }
    })
}

fn mib(bytes: usize) -> f64 {
    bytes as f64 / f64::from(1u32 << 20)
}

/// Run `plan`, print a summary, and fail with every failing case at once.
fn run_batch(batch: &str, base: u64, plan: &[Case], corpus: &[Original], baseline: &Baseline) {
    let cap = baseline.cap;
    let skip = skipped_cases();
    let started = Instant::now();
    let mut failures: Vec<String> = Vec::new();
    let (mut ran, mut parsed, mut rejected, mut skipped, mut hangs) = (0, 0, 0, 0, 0);
    let mut slowest: Option<(Duration, String)> = None;
    for case in plan {
        let line = case.line(corpus);
        if skip.contains(&case.index) {
            println!("case {}: skipped by {SKIP_VAR}: {line}", case.index);
            skipped += 1;
            continue;
        }
        let source = case.source(corpus);
        let bytes = build(source, &case.mutation, case.seed);
        if bytes != build(source, &case.mutation, case.seed) {
            failures.push(format!("{line}: built differently twice"));
            continue;
        }
        println!("case {}: {line} ({} B)", case.index, bytes.len());
        ran += 1;
        let case_started = Instant::now();
        let outcome = run_case(&format!("case {}", case.index), bytes, cap, pid_parse_chain);
        let took = case_started.elapsed();
        if slowest.as_ref().is_none_or(|(most, _)| took > *most) {
            slowest = Some((took, line.clone()));
        }
        match outcome {
            Ok(Passed { parsed: true, .. }) => parsed += 1,
            Ok(Passed { parsed: false, .. }) => rejected += 1,
            Err(failure) => {
                let shared = hangs > 0 && matches!(failure, Failure::OverAllocated { .. });
                let note = if shared {
                    " (a hung case's thread is still running and shares the counter)"
                } else {
                    ""
                };
                failures.push(format!("{line}: {failure}{note}"));
                if matches!(failure, Failure::Hung) {
                    hangs += 1;
                    if hangs == MAX_HANGS {
                        break;
                    }
                }
            }
        }
    }
    let stopped = if hangs == MAX_HANGS {
        format!(", stopped after {MAX_HANGS} hangs")
    } else {
        String::new()
    };
    let slowest = slowest.map_or_else(
        || "none".to_owned(),
        |(took, line)| format!("{took:.2?} ({line})"),
    );
    println!(
        "{batch} batch: {} cases, {ran} run ({parsed} parsed Ok, {rejected} Err), \
         {} failed, {skipped} skipped{stopped}, in {:.1?}; slowest {slowest}; \
         cap {}; base seed 0x{base:X}",
        plan.len(),
        failures.len(),
        started.elapsed(),
        baseline.cap_text(),
    );
    assert!(
        failures.is_empty(),
        "{batch} batch: {} of {} cases failed (cap {cap} B, base seed 0x{base:X}){stopped}:\n{}",
        failures.len(),
        plan.len(),
        failures.join("\n"),
    );
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn the_six_originals_set_the_allocation_cap() {
    let _serial = lock(&SERIAL);
    if corpus().is_empty() {
        eprintln!("skip: no corpus drawing under test-file/; the cap stays at its floor");
        return;
    }
    let baseline = baseline();
    let mut failures = Vec::new();
    for measured in &baseline.originals {
        match &measured.outcome {
            Ok(Passed { parsed, largest }) => {
                println!(
                    "{}: largest single allocation {largest} B ({:.2} MiB), parsed {}, in {:.2?}",
                    measured.name,
                    mib(*largest),
                    if *parsed { "Ok" } else { "Err" },
                    measured.elapsed,
                );
                if !parsed {
                    failures.push(format!("{}: parse_reader said Err", measured.name));
                }
            }
            Err(failure) => {
                println!("{}: {failure}", measured.name);
                failures.push(format!("{}: {failure}", measured.name));
            }
        }
    }
    println!("allocation cap = {}", baseline.cap_text());
    assert!(
        failures.is_empty(),
        "the unmutated drawings must go through the chain cleanly:\n{}",
        failures.join("\n"),
    );
}

#[test]
fn every_case_is_built_the_same_twice() {
    let _serial = lock(&SERIAL);
    let corpus = corpus();
    let base = base_seed();
    let plan = default_plan(base, corpus);
    assert_eq!(
        plan.len(),
        1 + RANDOM_LENGTHS.len() + 1 + (DEFAULT_PICKS.len() + 1) * corpus.len(),
        "the default batch is empty 1 + random 9 + 15 per drawing",
    );
    assert_eq!(plan, default_plan(base, corpus), "default plan drifted");
    let extended = extended_plan(base, corpus);
    assert_eq!(
        extended.len(),
        1 + RANDOM_LENGTHS.len() + EXTENDED_RANDOM_DRAWS + EXTENDED_PER_FILE * corpus.len(),
    );
    assert_eq!(
        extended,
        extended_plan(base, corpus),
        "extended plan drifted"
    );
    let differ: Vec<String> = plan
        .iter()
        .filter(|case| {
            let source = case.source(corpus);
            build(source, &case.mutation, case.seed) != build(source, &case.mutation, case.seed)
        })
        .map(|case| case.line(corpus))
        .collect();
    assert!(
        differ.is_empty(),
        "built differently twice:\n{}",
        differ.join("\n"),
    );
}

/// The executor can go red: a planted panic and an allocation over the cap
/// both come back as failures. (A planted hang would cost 10 s and a leaked
/// thread, so the timeout path is left to `recv_timeout`.)
#[test]
fn the_executor_reports_a_planted_panic_and_overallocation() {
    fn panics(_: &[u8]) -> bool {
        panic!("planted panic")
    }
    fn allocates_two_mib(_: &[u8]) -> bool {
        black_box(vec![0u8; 2 << 20]);
        true
    }
    let _serial = lock(&SERIAL);
    match run_case("planted panic", Vec::new(), usize::MAX, panics) {
        Err(Failure::Panicked(text)) => assert!(
            text.contains("planted panic") && text.contains("arbitrary_bytes_never_panic.rs"),
            "the report lost the message or the location: {text}",
        ),
        other => panic!("a planted panic came back as {other:?}"),
    }
    match run_case("planted allocation", Vec::new(), 1 << 20, allocates_two_mib) {
        Err(Failure::OverAllocated { largest, cap }) => {
            assert!(
                largest >= 2 << 20 && cap == 1 << 20,
                "{largest} B, cap {cap} B"
            );
        }
        other => panic!("a 2 MiB allocation under a 1 MiB cap came back as {other:?}"),
    }
}

#[test]
fn the_default_batch_never_panics_hangs_or_overallocates() {
    let _serial = lock(&SERIAL);
    let corpus = corpus();
    let base = base_seed();
    let baseline = baseline();
    run_batch(
        "default",
        base,
        &default_plan(base, corpus),
        corpus,
        baseline,
    );
}

#[test]
#[ignore = "thousands of cases: cargo test --release --test arbitrary_bytes_never_panic -- --ignored"]
fn the_extended_batch_never_panics_hangs_or_overallocates() {
    let _serial = lock(&SERIAL);
    let corpus = corpus();
    let base = base_seed();
    let baseline = baseline();
    run_batch(
        "extended",
        base,
        &extended_plan(base, corpus),
        corpus,
        baseline,
    );
}
