//! Phase 29 Slice M probe: characterize the last multi-fixture common
//! unregistered top-level paths — `/JSitesList` and
//! `/TaggedTxtData/Revision` — across the local PID fixture set.
//!
//! Read-only investigation tooling. For each stream it prints size, a
//! bounded hex window, UTF-16LE / UTF-8 interpretations, and whether the
//! existing `parse_tagged_stg_list` (UTF-16 storage-list) parser would
//! accept the bytes. It prints markdown, does not name fields, and does
//! not promote parser semantics.

use std::path::Path;

use pid_parse::parsers::tagged_stg_list::parse_tagged_stg_list;
use pid_parse::PidParser;

const FIXTURES: &[(&str, &str)] = &[
    ("d06", "test-file/D06.pid"),
    ("nonascii-process-1", "test-file/工艺管道及仪表流程-1.pid"),
    ("dwg0201", "test-file/DWG-0201GP06-01.pid"),
    ("dwg0202", "test-file/DWG-0202GP06-01.pid"),
    (
        "publish-a01",
        "test-file/export-test/publish-data/A01/A01.pid",
    ),
    (
        "publish-dwg0202",
        "test-file/export-test/publish-data/DWG-0202GP06-01/DWG-0202GP06-01.pid",
    ),
];

const TARGETS: &[&str] = &["JSitesList", "TaggedTxtData/Revision"];
const HEX_WINDOW_LEN: usize = 96;

fn hex_window(bytes: &[u8], max_len: usize) -> String {
    bytes
        .iter()
        .take(max_len)
        .map(|b| format!("{b:02X}"))
        .collect::<Vec<_>>()
        .join(" ")
}

fn utf16_preview(bytes: &[u8], max_chars: usize) -> String {
    let units: Vec<u16> = bytes
        .as_chunks::<2>()
        .0
        .iter()
        .take(max_chars)
        .map(|c| u16::from_le_bytes([c[0], c[1]]))
        .collect();
    String::from_utf16_lossy(&units)
        .chars()
        .map(|c| if c.is_control() { '·' } else { c })
        .collect()
}

fn utf8_preview(bytes: &[u8], max_len: usize) -> String {
    String::from_utf8_lossy(&bytes[..bytes.len().min(max_len)])
        .chars()
        .map(|c| if c.is_control() { '·' } else { c })
        .collect()
}

fn main() {
    println!("# Phase 29 Slice M: Unregistered Tail Probe (JSitesList / Revision)");
    println!();
    println!("> Generated by `cargo run --example probe_phase29_unregistered_tails`.");
    println!("> Investigation-only output; no parser semantics are promoted.");
    println!();

    let parser = PidParser::new();

    for (fixture_id, fixture_path) in FIXTURES {
        if !Path::new(fixture_path).exists() {
            eprintln!("skip: fixture not found: {fixture_path}");
            continue;
        }
        let Ok(pkg) = parser.parse_package(fixture_path) else {
            eprintln!("skip: failed to parse fixture: {fixture_path}");
            continue;
        };
        for target in TARGETS {
            let Some((path, stream)) = pkg
                .streams
                .iter()
                .find(|(p, _)| p.trim_start_matches('/') == *target)
            else {
                continue;
            };
            let data = stream.data.as_slice();
            println!("## `{fixture_id}` `{path}` ({} bytes)", data.len());
            println!();
            println!("- Hex: `{}`", hex_window(data, HEX_WINDOW_LEN));
            println!("- UTF-16LE: `{}`", utf16_preview(data, 48));
            println!("- UTF-8: `{}`", utf8_preview(data, 96));
            match parse_tagged_stg_list(data) {
                Some(list) => println!("- `parse_tagged_stg_list`: accepted -> {list:?}"),
                None => println!("- `parse_tagged_stg_list`: rejected"),
            }
            println!();
        }
    }

    println!("## Guardrails");
    println!();
    println!("- Previews are bounded samples for human review, not extracted product data.");
    println!("- Parser acceptance here justifies a registration slice, not new field names.");
}
