//! Phase 29 Slice L probe: test whether nested `JSite*` registry child
//! streams reuse the formats proven for their top-level twins.
//!
//! This is read-only investigation tooling. For every fixture it finds
//! one-level nested `JSite<id>/<child>` streams whose child name matches
//! a registry family with an existing trace-aware parser
//! (`PSMclustertable`, `PSMroots`, `PSMsegmenttable`, `DocVersion2`,
//! `DocVersion3`, `AppObject`, `\x05SummaryInformation`,
//! `\x05DocumentSummaryInformation`) and runs the **existing** top-level
//! parser on the nested bytes, reporting how much each one claims. The
//! parsers self-validate (magic / record shape gates), so a nested twin
//! either parses like its top-level counterpart or claims ~nothing.
//!
//! It prints markdown, does not name fields, and does not promote parser
//! semantics.

use std::path::Path;

use pid_parse::{ParserTraceBuilder, PidParser};

const FIXTURES: &[(&str, &str)] = &[
    ("d06", "test-file/D06.pid"),
    ("nonascii-process-1", "test-file/工艺管道及仪表流程-1.pid"),
    ("dwg0201", "test-file/DWG-0201GP06-01.pid"),
    ("dwg0202", "test-file/DWG-0202GP06-01.pid"),
    (
        "publish-a01",
        "test-file/export-test/publish-data/A01/A01.pid",
    ),
    (
        "publish-dwg0202",
        "test-file/export-test/publish-data/DWG-0202GP06-01/DWG-0202GP06-01.pid",
    ),
];

fn nested_jsite_child(path: &str) -> Option<(&str, &str)> {
    let trimmed = path.trim_start_matches('/');
    let (parent, child) = trimmed.split_once('/')?;
    if !parent.starts_with("JSite") || child.contains('/') {
        return None;
    }
    Some((parent, child))
}

fn run_parser(child: &str, data: &[u8]) -> Option<(&'static str, u64, u64)> {
    use pid_parse::parsers;
    let (name, builder) = match child {
        "PSMclustertable" => ("parse_psm_cluster_table", {
            let mut b = ParserTraceBuilder::new("parse_psm_cluster_table");
            let _ = parsers::psm_tables::parse_psm_cluster_table_with_trace(data, &mut b);
            b
        }),
        "PSMroots" => ("parse_psm_roots", {
            let mut b = ParserTraceBuilder::new("parse_psm_roots");
            let _ = parsers::psm_tables::parse_psm_roots_with_trace(data, &mut b);
            b
        }),
        "PSMsegmenttable" => ("parse_psm_segment_table", {
            let mut b = ParserTraceBuilder::new("parse_psm_segment_table");
            let _ = parsers::psm_tables::parse_psm_segment_table_with_trace(data, &mut b);
            b
        }),
        "DocVersion2" => ("parse_doc_version2", {
            let mut b = ParserTraceBuilder::new("parse_doc_version2");
            let _ = parsers::doc_version2::parse_doc_version2_with_trace(data, &mut b);
            b
        }),
        "DocVersion3" => ("parse_doc_version3", {
            let mut b = ParserTraceBuilder::new("parse_doc_version3");
            let _ = parsers::doc_version::parse_doc_version3_with_trace(data, &mut b);
            b
        }),
        "AppObject" => ("parse_app_object", {
            let mut b = ParserTraceBuilder::new("parse_app_object");
            let _ = parsers::app_object::parse_app_object_with_trace(data, &mut b);
            b
        }),
        "\u{5}SummaryInformation" | "\u{5}DocumentSummaryInformation" => {
            ("parse_summary_property_set", {
                let mut b = ParserTraceBuilder::new("parse_summary_property_set");
                let _ = parsers::summary::parse_summary_property_set_with_trace(data, &mut b);
                b
            })
        }
        _ => return None,
    };
    let trace = builder.build("probe", data.len() as u64);
    Some((name, trace.consumed_bytes(), trace.leftover_bytes()))
}

fn main() {
    println!("# Phase 29: Nested JSite Registry Stream Probe");
    println!();
    println!("> Generated by `cargo run --example probe_phase29_nested_registry_streams`.");
    println!("> Investigation-only output; no parser semantics are promoted.");
    println!();
    println!("| Fixture | Stream | Bytes | Parser | Consumed | Leftover | Ratio |");
    println!("|---|---|---:|---|---:|---:|---:|");

    let parser = PidParser::new();
    let mut probed = 0usize;
    let mut fully = 0usize;
    let mut total_bytes = 0u64;
    let mut total_consumed = 0u64;

    for (fixture_id, fixture_path) in FIXTURES {
        if !Path::new(fixture_path).exists() {
            eprintln!("skip: fixture not found: {fixture_path}");
            continue;
        }
        let Ok(pkg) = parser.parse_package(fixture_path) else {
            eprintln!("skip: failed to parse fixture: {fixture_path}");
            continue;
        };
        let mut paths: Vec<&String> = pkg.streams.keys().collect();
        paths.sort();
        for path in paths {
            let Some((_, child)) = nested_jsite_child(path) else {
                continue;
            };
            let data = pkg.streams[path].data.as_slice();
            let Some((parser_name, consumed, leftover)) = run_parser(child, data) else {
                continue;
            };
            let display_path = path.replace('\u{5}', "\\x05");
            println!(
                "| `{}` | `{}` | {} | `{}` | {} | {} | {:.4} |",
                fixture_id,
                display_path,
                data.len(),
                parser_name,
                consumed,
                leftover,
                if data.is_empty() {
                    0.0
                } else {
                    consumed as f64 / data.len() as f64
                }
            );
            probed += 1;
            if leftover == 0 {
                fully += 1;
            }
            total_bytes += data.len() as u64;
            total_consumed += consumed;
        }
    }

    println!();
    println!(
        "Streams probed: {probed} | fully consumed: {fully} | bytes: {total_bytes} | consumed: {total_consumed} ({:.4})",
        if total_bytes == 0 {
            0.0
        } else {
            total_consumed as f64 / total_bytes as f64
        }
    );
    println!();
    println!("## Guardrails");
    println!();
    println!("- Parser claims are gate-validated by the existing top-level parsers; this probe adds no semantics.");
    println!(
        "- A passing parse justifies nested byte-audit registration, not ownership decisions."
    );
}
