//! Phase 29 probe: characterize the `/StyleCluster` prefix between the
//! 16-byte cluster header and the end-anchored body record chain.
//!
//! Read-only investigation tooling. Tests the GUID-table hypothesis from
//! `docs/analysis/2026-06-08-phase29-stylecluster-leftover-triage.md`:
//! ten zero bytes, a `u16` count, then `count` 16-byte CLSID-shaped
//! entries — and dumps whatever follows up to the chain start. Prints
//! markdown; promotes no semantics.

use std::collections::BTreeMap;
use std::path::Path;

use pid_parse::parsers::cluster_header::decode_style_cluster_body_records;
use pid_parse::PidParser;

const FIXTURES: &[(&str, &str)] = &[
    ("d06", "test-file/D06.pid"),
    ("nonascii-process-1", "test-file/工艺管道及仪表流程-1.pid"),
    ("dwg0201", "test-file/DWG-0201GP06-01.pid"),
    ("dwg0202", "test-file/DWG-0202GP06-01.pid"),
    (
        "publish-a01",
        "test-file/export-test/publish-data/A01/A01.pid",
    ),
    (
        "publish-dwg0202",
        "test-file/export-test/publish-data/DWG-0202GP06-01/DWG-0202GP06-01.pid",
    ),
];

fn guid_string(bytes: &[u8]) -> String {
    let d1 = u32::from_le_bytes([bytes[0], bytes[1], bytes[2], bytes[3]]);
    let d2 = u16::from_le_bytes([bytes[4], bytes[5]]);
    let d3 = u16::from_le_bytes([bytes[6], bytes[7]]);
    format!(
        "{{{d1:08X}-{d2:04X}-{d3:04X}-{:02X}{:02X}-{:02X}{:02X}{:02X}{:02X}{:02X}{:02X}}}",
        bytes[8], bytes[9], bytes[10], bytes[11], bytes[12], bytes[13], bytes[14], bytes[15]
    )
}

fn hex(bytes: &[u8]) -> String {
    bytes
        .iter()
        .map(|b| format!("{b:02X}"))
        .collect::<Vec<_>>()
        .join(" ")
}

/// Scan a region for UTF-16LE printable ASCII runs (>= 4 chars).
fn utf16_runs(bytes: &[u8], start: usize, end: usize) -> Vec<(usize, String)> {
    let mut out = Vec::new();
    let end = end.min(bytes.len());
    let mut cursor = start;
    while cursor + 2 <= end {
        let mut probe = cursor;
        let mut units = Vec::new();
        while probe + 2 <= end {
            let unit = u16::from_le_bytes([bytes[probe], bytes[probe + 1]]);
            if (0x20..=0x7E).contains(&unit) {
                units.push(unit);
                probe += 2;
            } else {
                break;
            }
        }
        if units.len() >= 4 {
            out.push((cursor, String::from_utf16_lossy(&units)));
            cursor = probe;
        } else {
            cursor += 1;
        }
    }
    out
}

fn main() {
    println!("# Phase 29: StyleCluster Prefix Characterization");
    println!();
    println!("> Generated by `cargo run --example probe_phase29_stylecluster_prefix`.");
    println!("> Investigation-only output; no parser semantics are promoted.");
    println!();

    let parser = PidParser::new();
    let mut guid_occurrence: BTreeMap<String, Vec<&'static str>> = BTreeMap::new();
    let mut prefixes: Vec<(&'static str, Vec<u8>)> = Vec::new();

    for (fixture_id, fixture_path) in FIXTURES {
        if !Path::new(fixture_path).exists() {
            eprintln!("skip: fixture not found: {fixture_path}");
            continue;
        }
        let Ok(pkg) = parser.parse_package(fixture_path) else {
            eprintln!("skip: failed to parse fixture: {fixture_path}");
            continue;
        };
        let Some(stream) = pkg
            .streams
            .iter()
            .find(|(path, _)| path.trim_start_matches('/') == "StyleCluster")
            .map(|(_, s)| s)
        else {
            eprintln!("skip: no StyleCluster in {fixture_path}");
            continue;
        };
        let data = stream.data.as_slice();
        let records = decode_style_cluster_body_records(data);
        let Some(chain_start) = records.first().map(|r| r.byte_range.start) else {
            eprintln!("skip: no chain in {fixture_path}");
            continue;
        };

        println!(
            "## Fixture `{fixture_id}` (prefix `16..{chain_start}`, {} bytes)",
            chain_start - 16
        );
        println!();
        prefixes.push((fixture_id, data[16..chain_start].to_vec()));

        // Hypothesis step 1: ten zero bytes at [16..26).
        let zeros = &data[16..26];
        println!(
            "- `[16..26)` ten-byte prologue: `{}` (all zero: {})",
            hex(zeros),
            zeros.iter().all(|&b| b == 0)
        );

        // Hypothesis step 2: u16 count at [26..28).
        let count = u16::from_le_bytes([data[26], data[27]]) as usize;
        println!("- `[26..28)` u16 count: {count}");

        // Hypothesis step 3: stride comparison. The tight 16-byte window
        // showed misalignment artifacts, so try GUID + trailing-bytes
        // strides and score each by how many entries look like a
        // plausible GUID (version-1 `data3` nibble, or all-zero).
        let table_start = 28usize;
        let plausible = |off: usize| -> bool {
            let Some(bytes) = data.get(off..off + 16) else {
                return false;
            };
            if bytes.iter().all(|&b| b == 0) {
                return true;
            }
            // data3 = bytes[6..8] LE; COM time-based GUIDs carry version
            // nibble 1 (e.g. 0x11D0, 0x11CE).
            let data3 = u16::from_le_bytes([bytes[6], bytes[7]]);
            (data3 >> 12) == 0x1
        };
        for stride in [16usize, 20, 24, 28, 32] {
            let table_end = table_start + count * stride;
            if table_end > chain_start {
                println!("- stride {stride}: table would end at {table_end} > chain start, skip");
                continue;
            }
            let ok = (0..count)
                .filter(|i| plausible(table_start + i * stride))
                .count();
            println!("- stride {stride}: {ok}/{count} plausible GUID entries");
        }

        // Dump stride-24 entries (GUID + 8 trailing bytes) for review.
        let stride = 24usize;
        let table_end = table_start + count * stride;
        if table_end <= chain_start {
            println!("- stride-24 entries (GUID + 8 trailing bytes):");
            for i in 0..count {
                let off = table_start + i * stride;
                let g = guid_string(&data[off..off + 16]);
                let tail = hex(&data[off + 16..off + 24]);
                println!("  {:>2}. `{g}` + `{tail}`", i + 1);
                guid_occurrence.entry(g).or_default().push(fixture_id);
            }
            println!("- stride-24 table end: {table_end} (chain start {chain_start})");
        }

        // Remainder between the stride-24 table and chain start.
        let rem_start = (table_start + count * 24).min(chain_start);
        let rem_len = chain_start - rem_start;
        println!(
            "- Remainder `[{rem_start}..{chain_start})` ({rem_len} bytes) before chain start:"
        );
        let window_end = (rem_start + 96).min(chain_start);
        println!(
            "  - hex (first {} bytes): `{}`",
            window_end - rem_start,
            hex(&data[rem_start..window_end])
        );
        let runs = utf16_runs(data, rem_start, chain_start);
        println!("  - UTF-16LE runs (>=4 chars): {}", runs.len());
        for (off, text) in runs.iter().take(10) {
            println!("    - @{off}: `{text}`");
        }
        // Tail of the remainder (last 32 bytes before chain start).
        let tail_start = chain_start.saturating_sub(32).max(rem_start);
        println!(
            "  - hex (last {} bytes): `{}`",
            chain_start - tail_start,
            hex(&data[tail_start..chain_start])
        );
        println!();
    }

    if let Some((base_id, base)) = prefixes.first() {
        println!("## Cross-Fixture Constant-Region Analysis (baseline `{base_id}`)");
        println!();
        println!("| Fixture | Prefix len | Common prefix with baseline (bytes from offset 16) |");
        println!("|---|---:|---:|");
        for (id, p) in &prefixes {
            let common = base
                .iter()
                .zip(p.iter())
                .take_while(|(a, b)| a == b)
                .count();
            println!("| `{id}` | {} | {common} |", p.len());
        }
        println!();
    }

    println!("## GUID Occurrence Across Fixtures");
    println!();
    println!("| GUID | Fixtures |");
    println!("|---|---|");
    for (guid, fixtures) in &guid_occurrence {
        println!(
            "| `{guid}` | {} ({}) |",
            fixtures.len(),
            fixtures.join(", ")
        );
    }

    println!();
    println!("## Guardrails");
    println!();
    println!("- GUID-shaped bytes are layout evidence; no registry / IDA identity is claimed.");
    println!("- The remainder region stays uncharacterized until structure is proven.");
}
