//! Phase 29 Slice D-J probe: test whether nested `JSite*` cluster child
//! streams reuse the body layouts proven for their top-level twins.
//!
//! This is read-only investigation tooling. For every fixture it finds
//! one-level nested `JSite<id>/PSMcluster0`, `JSite<id>/StyleCluster`,
//! and `JSite<id>/Unclustered Dynamic Attributes` streams and runs the
//! **existing** audit-only walkers on their bytes:
//!
//! - [`pid_parse::parsers::cluster_header::decode_psm_cluster0_body_records`]
//!   (header + string table + 10-byte prologue + end-anchored chain),
//! - [`pid_parse::parsers::cluster_header::decode_style_cluster_body_records`]
//!   (header + prefix + earliest end-anchored chain),
//! - [`pid_parse::parsers::cluster_header::decode_unclustered_da_body_records`]
//!   (8-byte magic+counter prologue + end-anchored chain).
//!
//! The walkers' strict full-coverage gates do the verification: a nested
//! stream either decodes end-to-end like its top-level twin or reports
//! zero records. It prints markdown, does not name fields, and does not
//! promote parser semantics.

use std::path::Path;

use pid_parse::parsers::cluster_header::{
    decode_psm_cluster0_body_records, decode_style_cluster_body_records,
    decode_unclustered_da_body_records, parse_header,
};
use pid_parse::PidParser;

const FIXTURES: &[(&str, &str)] = &[
    ("d06", "test-file/D06.pid"),
    ("nonascii-process-1", "test-file/工艺管道及仪表流程-1.pid"),
    ("dwg0201", "test-file/DWG-0201GP06-01.pid"),
    ("dwg0202", "test-file/DWG-0202GP06-01.pid"),
    (
        "publish-a01",
        "test-file/export-test/publish-data/A01/A01.pid",
    ),
    (
        "publish-dwg0202",
        "test-file/export-test/publish-data/DWG-0202GP06-01/DWG-0202GP06-01.pid",
    ),
];

/// Split a stream path into a one-level nested JSite child:
/// `/JSite793/PSMcluster0` → `("JSite793", "PSMcluster0")`.
fn nested_jsite_child(path: &str) -> Option<(&str, &str)> {
    let trimmed = path.trim_start_matches('/');
    let (parent, child) = trimmed.split_once('/')?;
    if !parent.starts_with("JSite") || child.contains('/') {
        return None;
    }
    Some((parent, child))
}

fn main() {
    println!("# Phase 29: Nested JSite Cluster Body Probe");
    println!();
    println!("> Generated by `cargo run --example probe_phase29_nested_cluster_bodies`.");
    println!("> Investigation-only output; no parser semantics are promoted.");
    println!();
    println!("| Fixture | Stream | Bytes | record_count | Walker | Records | End-anchored | Chain start | Coverage of stream |");
    println!("|---|---|---:|---:|---|---:|---|---:|---:|");

    let parser = PidParser::new();
    let mut totals: (usize, usize, u64, u64) = (0, 0, 0, 0); // (streams, walked, bytes, covered)

    for (fixture_id, fixture_path) in FIXTURES {
        if !Path::new(fixture_path).exists() {
            eprintln!("skip: fixture not found: {fixture_path}");
            continue;
        }
        let Ok(pkg) = parser.parse_package(fixture_path) else {
            eprintln!("skip: failed to parse fixture: {fixture_path}");
            continue;
        };

        let mut paths: Vec<&String> = pkg.streams.keys().collect();
        paths.sort();
        for path in paths {
            let Some((_, child)) = nested_jsite_child(path) else {
                continue;
            };
            let walker = match child {
                "PSMcluster0" => "psm_cluster0",
                "StyleCluster" => "style_cluster",
                "Unclustered Dynamic Attributes" => "unclustered_da",
                _ => continue,
            };
            let data = pkg.streams[path].data.as_slice();
            let header = parse_header(data);
            let records = match walker {
                "psm_cluster0" => decode_psm_cluster0_body_records(data),
                "style_cluster" => decode_style_cluster_body_records(data),
                _ => decode_unclustered_da_body_records(data),
            };
            let chain_start = records.first().map(|r| r.byte_range.start);
            let chain_end = records.last().map(|r| r.byte_range.end);
            let covered: u64 = records
                .iter()
                .map(|r| (r.byte_range.end - r.byte_range.start) as u64)
                .sum();
            let coverage = if data.is_empty() {
                0.0
            } else {
                covered as f64 / data.len() as f64
            };
            println!(
                "| `{}` | `{}` | {} | {} | `{}` | {} | {} | {} | {:.4} |",
                fixture_id,
                path,
                data.len(),
                header
                    .as_ref()
                    .map(|h| h.record_count.to_string())
                    .unwrap_or_else(|| "-".to_string()),
                walker,
                records.len(),
                match chain_end {
                    Some(end) if end == data.len() => "yes",
                    Some(_) => "no",
                    None => "-",
                },
                chain_start
                    .map(|s| s.to_string())
                    .unwrap_or_else(|| "-".to_string()),
                coverage
            );
            totals.0 += 1;
            if !records.is_empty() {
                totals.1 += 1;
            }
            totals.2 += data.len() as u64;
            totals.3 += covered;
        }
    }

    println!();
    println!(
        "Streams probed: {} | walked end-to-end: {} | bytes: {} | chain-covered bytes: {} ({:.4})",
        totals.0,
        totals.1,
        totals.2,
        totals.3,
        if totals.2 == 0 {
            0.0
        } else {
            totals.3 as f64 / totals.2 as f64
        }
    );
    println!();
    println!("## Guardrails");
    println!();
    println!("- Walker results are byte-shape evidence; record type codes are not semantic names.");
    println!("- A passing gate justifies nested byte-audit accounting, not ownership or geometry semantics.");
}
